version: '3.7'

services:
  music_predictor_backend:
    image: music_predictor_backend
    container_name: music_predictor_backend
    command: poetry run python music_predictor_backend/main.py
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro
    restart: on-failure
    platform: linux/amd64
    build:
      dockerfile: Dockerfile