components:
  schemas:
    Body_predict_by_spectorgrams_api_v1_model_predict_by_spectorgrams_post:
      properties:
        files:
          items:
            format: binary
            type: string
          title: Files
          type: array
      required:
      - files
      title: Body_predict_by_spectorgrams_api_v1_model_predict_by_spectorgrams_post
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ListPredictResponses:
      properties:
        predicted_genres:
          default: []
          items:
            $ref: '#/components/schemas/PredictResponse'
          title: Predicted Genres
          type: array
      title: ListPredictResponses
      type: object
    PredictResponse:
      properties:
        genres:
          items:
            type: string
          title: Genres
          type: array
      required:
      - genres
      title: PredictResponse
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: docs_redirect__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Docs Redirect
  /api/v1/model/predict_by_spectorgrams:
    post:
      operationId: predict_by_spectorgrams_api_v1_model_predict_by_spectorgrams_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_predict_by_spectorgrams_api_v1_model_predict_by_spectorgrams_post'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPredictResponses'
          description: Successful Response
        '404':
          description: Not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Predict By Spectorgrams
      tags:
      - Music
